FROM lambci/lambda:build-provided
MAINTAINER Daniel Boline

RUN apt-get update && \
    apt-get install -y curl pkg-config checkinstall gcc libssl-dev ca-certificates \
            file build-essential autoconf automake autotools-dev libtool xutils-dev \
            git libusb-dev libxml2-dev libpq-dev && \
    rm -rf /var/lib/apt/lists/* && \
    curl https://sh.rustup.rs > rustup.sh && \
    sh rustup.sh -y && \
    . ~/.cargo/env

WORKDIR /rust-auth-server

ADD Cargo.toml /rust-auth-server
ADD src /rust-auth-server/src
ADD scripts /rust-auth-server/scripts
ADD Makefile /rust-auth-server
ADD static /rust-auth-server/static
