# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true


# nightly

# normalize_comments = true
# wrap_comments = true
# format_strings = true
# merge_imports = true
